- src: https://github.com/vterdunov/ansible-apt
  name: apt

- src: https://github.com/ANXS/postgresql.git
  scm: git
  name: postgresql

- src: https://github.com/geerlingguy/ansible-role-ntp
  name: ntp

- src: https://github.com/fubarhouse/ansible-role-golang
  name: golang
